/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
    conceptsSidebar: [{ type: "autogenerated", dirName: "concepts" }],
    adminIdentityApiAdminSidebar: [
        ...require("./docs/adminidentity/api/graphql-admin/reference/sidebar-schema.js")
            .schemaSidebar,
    ],
    demandApiAdminSidebar: [
        ...require("./docs/demand/api/graphql-admin/reference/sidebar-schema.js")
            .schemaSidebar,
    ],
    demandApiStorefrontSidebar: [
        ...require("./docs/demand/api/graphql-storefront/reference/sidebar-schema.js")
            .schemaSidebar,
    ],
    supplyApiAdminSidebar: [
        ...require("./docs/supply/api/graphql-admin/reference/sidebar-schema.js")
            .schemaSidebar,
    ],
};
